build:
  version: "2.0"

accounts:
  message: "Welcome to GoldBank accounts related QA APIs "
  contactDetails:
    name: "Suraj Sharma - Developer"
    email: "suraj.sharma@goldank.com"
  onCallSupport:
    - (123) 456-789
    - (123) 456-789